- name: Install Composer package
  yum:                                                                                                                                                                        
    name: composer
    state: present

