---
- name: Procure epel repository
  yum:
    name: epel-release
    state: present
  when: skipreposetup is not defined or not skipreposetup

- name: Procure packages
  yum:
    name:
      - redis
