---
redis_arrangement:
  server: True
  source: epel
  version: 3.2
  rhscl_exposed: False
  bind: 127.0.0.1
  protectedmode: "yes"
  port: 6379
  tcpbacklog: 511
  timeout: 0
  tcpkeepalive: 300
  daemonize: "no"
  supervised: "no"
  pidfile: /var/run/redis_6379.pid
  loglevel: notice
  logfile: /var/log/redis/redis.log
  databases: 16
  stopwritesonbgsaveerror: "yes"
  rdbcompression: "yes"
  rdbchecksum: "yes"
  dbfilename: dump.rdb
  dir: /var/lib/redis
  slaveservestaledata: "yes"
  slavereadonly: "yes"
  repldisklesssync: "no"
  repldisklesssyncdelay: 5
  repldisabletcpnodelay: "no"
  slavepriority: 100
  appendonly: "no"
  appendfilename: "appendonly.aof"
  appendfsync: everysec
  noappendfsynconrewrite: "no"
  autoaofrewritepercentage: 100
  autoaofrewriteminsize: 64mb
  aofloadtruncated: "yes"
  luatimelimit: 5000
  slowloglogslowerthan: 10000
  slowlogmaxlen: 128
  latencymonitorthreshold: 0
  notifykeyspaceevents: '""'
  hashmaxziplistentries: 512
  hashmaxziplistvalue: 64
  listmaxziplistsize: 2
  listcompressdepth: 0
  setmaxintsetentries: 512
  zsetmaxziplistentries: 128
  zsetmaxziplistvalue: 64
  hllsparsemaxbytes: 3000
  activerehashing: "yes"
  hz: 10
  aofrewriteincrementalfsync: "yes"
