---
nginx_arrangement:
  user: nginx
  worker_processes: auto
  worker_connections: 1024
  pid: /usr/local/openresty/nginx/logs/nginx.pid
  access_log: /var/log/nginx/access.log
  access_log_level: main
  error_log: /var/log/nginx/error.log
  error_log_level: warn
  sendfile: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: 65
  types_hash_max_size: 2048
  server_name_in_redirect: "on"
  server_names_hash_bucket_size: 128
  client_max_body_size: 1m
  large_ch_buf:
    num: 4
    size: 8k
  gzip:
    auto:   "on"
    static: "off"
    min_length: 1000
    types:
      - text/plain
      - text/xml
      - application/json
      - application/xml
      - text/css
      - application/javascript
    proxied:
      - no-cache
      - no-store
      - private
      - expired
      - auth
