galaxy_info:
  author: Silicon Publishing OPS Team <ops@siliconpublishing.com>
  description: Setup Silicon Publishing Designer Admin servce user account and directory structure
  company: Silicon Publishing

  min_ansible_version: 2.9

dependencies:
  - csf
  - sshd
