- name: calculate resource constraints for Image Magick Policy
  include_tasks: constraint.yml
  when: ims.policy.resource is not defined or not ims.policy.resource

- name: include a suitable task file
  include_tasks: "{{ task_file }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml"
        - "generic_{{ ansible_os_family|lower }}.yml"
      skip: False
  loop_control:
    loop_var: task_file
