- debug:
    msg: "generic_{{ ansible_os_family|lower }}"

- name: manage packages
  include_tasks: "{{ task_file }}"
  with_first_found:
    - files:
        - "{{ansible_distribution|lower}}{{ansible_distribution_major_version}}.yml"
        - "generic_{{ ansible_os_family|lower }}.yml"
      skip: False
  loop_control:
    loop_var: task_file

- name: set defaults
  import_tasks: default_configuration.yml
