---
- name: Add community MariaDB YUM repository
  yum_repository:
    name: mariadb
    description: MariaDB YUM repository
    baseurl: >
      http://yum.mariadb.org/{{ mariadb_vars.version }}/centos{{ ansible_distribution_major_version }}-amd64
  changed_when: False
  when: skipreposetup is not defined or not skipreposetup

- name: Register community MariaDB YUM repository gpg key
  rpm_key:
    state: present
    key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    validate_certs: False # Temporary workaround
  when: skipreposetup is not defined or not skipreposetup
                          
- name: Install MariaDB client packages
  yum:
    name:
      - MariaDB-client
      - MySQL-python
  when: mariadb_vars.client

- name: Install MariaDB server packages
  yum:
    name:
      - MariaDB-server
  when: mariadb_vars.server
