---
el_packages:
  - wget
  - net-tools
  - unzip
  - tar
  - bzip2
  - gzip
  - bind-utils
  - perl-lib
  - perl-Math-BigInt
  - perl-File-Copy
  - perl-libwww-perl
  - perl-LWP-Protocol-https

csf_override: {}
csf_arrangement:
  allow: []
  ignore:
    - "127.0.0.1"
  tcp_in:
    - "22"
  tcp_out:
    - 20
    - 21
    - 22
    - 25
    - 53
    - 80
    - 110
    - 113
    - 443
    - 587
    - 993
    - 995
    - "1025:65535"
  udp_in: []
  udp_out:
    - 20
    - 21
    - 53
    - 111
    - 113
    - 123
    - 635
    - "1025:65535"
  pre: '#!/bin/bash'
  post: '#!/bin/bash'
  sendmail_binary: '/bin/true'
