---
- name: "Make sure Red Hat/CentOS Software Collections are available"
  yum:
    pkg: "centos-release-scl"
    state: latest
  when: skipreposetup is not defined or not skipreposetup

- name: "Procure php{{ php_vars.version }} binaries"
  yum:
    pkg: "rh-php{{ php_vars.version }}"
    state: "{{ php_vars.state }}"

- name: "Procure php{{ php_vars.version }} FPM daemon"
  yum:
    pkg: "rh-php{{ php_vars.version }}-php-fpm"
    state: "{{ php_vars.state }}"
  when: php_vars.with_fpm

- name: "Procure php{{ php_vars.version }} Apache module"
  yum:
    pkg: "rh-php{{ php_vars.version }}-php"
    state: "{{ php_vars.state }}"
  when: php_vars.with_apache

- name: "Procure php{{ php_vars.version }} debug packages"
  yum:
    pkg:
      - "rh-php{{ php_vars.version }}-php-dbg"
      - "rh-php{{ php_vars.version }}-php-pecl-xdebug"
    state: present
  when: php_vars.with_devel

- name: Make sure debug packages are absent in Production
  yum:
    pkg:
      - "rh-php{{ php_vars.version }}-php-dbg"
      - "rh-php{{ php_vars.version }}-php-pecl-xdebug"
    state: absent
  when: not php_vars.with_devel

- name: Make sure xdebug.so is not active in Production
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/opt/rh/rh-php{{ php_vars.version }}/root/usr/lib64/php/modules/xdebug.so"
    - "/etc/opt/rh/rh-php{{ php_vars.version }}/php_vars.d/15-xdebug.ini"
  when: not php_vars.with_devel

- name: "Procure php{{ php_vars.version }} devel packages for use with pear/pecl"
  yum:
    pkg:
      - "rh-php{{ php_vars.version }}-php-devel"
      - gcc
      - cpp
    state: "{{ php_vars.state }}"

- name: "Compose list of core php{{ php_vars.version }} modules"
  set_fact:
    corem: >
      {% for item in php_vars.core_modules %}
      rh-php{{ php_vars.version }}-php-{{ item }} 
      {% endfor %}

- name: "Procure core modules"
  yum:
    pkg: "{{ corem.split() }}"
    state: "{{ php_vars.state }}"

- name: "Compose list of extra php{{ php_vars.version }} modules"
  set_fact:
    xtram: >
      {% for item in php_vars.extra_modules %}
      rh-php{{ php_vars.version }}-php-{{ item }} 
      {% endfor %}

- name: Procure extra modules (yum)
  yum:
    pkg: "{{ xtram.split() }}"
    state: "{{ php_vars.state }}"

- name: Procure extra modules (pecl)
  pear:
    executable: "/opt/rh/rh-php{{ php_vars.version }}/root/usr/bin/pear"
    name: pecl/msgpack
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable extra modules
  copy:
    content: extension=msgpack.so
    dest: "/etc/opt/rh/rh-php{{ php_vars.version }}/php.d/50-msgpack.ini"

- name: Set optional UMask
  copy:
    content: |
      [Service]
      UMask={{ php_vars.umask }}
    dest: "/etc/systemd/system/rh-php{{ php_vars.version }}-php-fpm.service.d/override.conf"
  when: php_vars.umask is defined and php_vars.umask

- set_fact:
    php_bindir: "/opt/rh/rh-php{{ php_vars.version }}/root/usr/bin"
