---
- name: procure EPEL repository
  yum:
    name: oracle-epel-release-el7
    state: present
  when: skipreposetup is not defined or not skipreposetup
  ignore_errors: True

- name: Procure packages
  yum:
    name:
      - nginx
      - nginx-filesystem
